//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M7PatientApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientNo { get; set; }
        public string PatientName { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
    }
}
