//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoungFashionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduct
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Table Table { get; set; }
    }
}
